version: "3.4"
services:
  frontend:
    image: node:alpine
    container_name: social_media_frontend
    ports:
      - "5173:5173"
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    command: npm run dev